version: '3.9'

services:

  postgres_db:
    image: postgres:16-alpine
    container_name: postgre-test-quind
    restart: always
    shm_size: 256mb

    environment:
      POSTGRES_USER: testquind
      POSTGRES_PASSWORD: testquind
      POSTGRES_DB: test_quind_dev

    ports:
      - "5432:5432"