spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_quind_dev
    username: testquind
    password: testquind
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql